
version: '3.7'
networks:
  networkuea:
services:
  # dspace-nginx:
  #     container_name: dspace-nginx
  #     image: nginx:latest
  #     build:
  #       context: ./nginx
  #       dockerfile: Dockerfile
  #     working_dir: /etc/nginx
  #     volumes:
  #       - ./nginx/config/:/etc/nginx
  #     networks:
  #       networkuea:
  #     depends_on:
  #       - dspace-angular
  #     ports:
  #       - "80:80"

  dspace-angular:
    container_name: dspace-angular
    environment:
      DSPACE_UI_SSL: 'false'
      DSPACE_UI_HOST: dspace-angular
      DSPACE_UI_PORT: '4000'
      DSPACE_UI_NAMESPACE: /
      DSPACE_REST_SSL: 'false'
      DSPACE_REST_HOST: dspace-beta.uea.edu.br
      # DSPACE_REST_HOST: vreli.com.br
      DSPACE_REST_PORT: 80
      DSPACE_REST_NAMESPACE: /server
    image: dspace/dspace-angular:dspace-7_x
    build:
      context: ..
      dockerfile: Dockerfile
    networks:
      networkuea:
    ports:
        - 4000:4000
    # - published: 4000
    #   target: 4000
    # - published: 9876
    #   target: 9876
    expose:
      - 4000
    stdin_open: true
    tty: true
